os = [
  "DirEntry",
  "F_OK",
  "GenericAlias",
  "Mapping",
  "MutableMapping",
  "O_APPEND",
  "O_BINARY",
  "O_CREAT",
  "O_EXCL",
  "O_NOINHERIT",
  "O_RANDOM",
  "O_RDONLY",
  "O_RDWR",
  "O_SEQUENTIAL",
  "O_SHORT_LIVED",
  "O_TEMPORARY",
  "O_TEXT",
  "O_TRUNC",
  "O_WRONLY",
  "P_DETACH",
  "P_NOWAIT",
  "P_NOWAITO",
  "P_OVERLAY",
  "P_WAIT",
  "PathLike",
  "R_OK",
  "SEEK_CUR",
  "SEEK_END",
  "SEEK_SET",
  "TMP_MAX",
  "W_OK",
  "X_OK",
  "_AddedDllDirectory",
  "_Environ",
  "__all__",
  "__builtins__",
  "__cached__",
  "__doc__",
  "__file__",
  "__loader__",
  "__name__",
  "__package__",
  "__spec__",
  "_check_methods",
  "_execvpe",
  "_exists",
  "_exit",
  "_fspath",
  "_get_exports_list",
  "_walk",
  "_wrap_close",
  "abc",
  "abort",
  "access",
  "add_dll_directory",
  "altsep",
  "chdir",
  "chmod",
  "close",
  "closerange",
  "cpu_count",
  "curdir",
  "defpath",
  "device_encoding",
  "devnull",
  "dup",
  "dup2",
  "environ",
  "error",
  "execl",
  "execle",
  "execlp",
  "execlpe",
  "execv",
  "execve",
  "execvp",
  "execvpe",
  "extsep",
  "fdopen",
  "fsdecode",
  "fsencode",
  "fspath",
  "fstat",
  "fsync",
  "ftruncate",
  "get_exec_path",
  "get_handle_inheritable",
  "get_inheritable",
  "get_terminal_size",
  "getcwd",
  "getcwdb",
  "getenv",
  "getlogin",
  "getpid",
  "getppid",
  "isatty",
  "kill",
  "linesep",
  "link",
  "listdir",
  "lseek",
  "lstat",
  "makedirs",
  "mkdir",
  "name",
  "open",
  "pardir",
  "path",
  "pathsep",
  "pipe",
  "popen",
  "putenv",
  "read",
  "readlink",
  "remove",
  "removedirs",
  "rename",
  "renames",
  "replace",
  "rmdir",
  "scandir",
  "sep",
  "set_handle_inheritable",
  "set_inheritable",
  "spawnl",
  "spawnle",
  "spawnv",
  "spawnve",
  "st",
  "startfile",
  "stat",
  "stat_result",
  "statvfs_result",
  "strerror",
  "supports_bytes_environ",
  "supports_dir_fd",
  "supports_effective_ids",
  "supports_fd",
  "supports_follow_symlinks",
  "symlink",
  "sys",
  "system",
  "terminal_size",
  "times",
  "times_result",
  "truncate",
  "umask",
  "uname_result",
  "unlink",
  "unsetenv",
  "urandom",
  "utime",
  "waitpid",
  "waitstatus_to_exitcode",
  "walk",
  "write",
]
hPrinter = [
  "Close",
  "Detach",
  "__abs__",
  "__add__",
  "__and__",
  "__bool__",
  "__class__",
  "__delattr__",
  "__dir__",
  "__divmod__",
  "__doc__",
  "__eq__",
  "__float__",
  "__format__",
  "__ge__",
  "__getattribute__",
  "__gt__",
  "__hash__",
  "__init__",
  "__init_subclass__",
  "__int__",
  "__invert__",
  "__le__",
  "__lshift__",
  "__lt__",
  "__mod__",
  "__mul__",
  "__ne__",
  "__neg__",
  "__new__",
  "__or__",
  "__pos__",
  "__pow__",
  "__radd__",
  "__rand__",
  "__rdivmod__",
  "__reduce__",
  "__reduce_ex__",
  "__repr__",
  "__rlshift__",
  "__rmod__",
  "__rmul__",
  "__ror__",
  "__rpow__",
  "__rrshift__",
  "__rshift__",
  "__rsub__",
  "__rxor__",
  "__setattr__",
  "__sizeof__",
  "__str__",
  "__sub__",
  "__subclasshook__",
  "__xor__",
  "close",
  "handle",
]

get_printer = {
  'pServerName': None, 
  'pPrinterName': 'POSSTORE PS-7', 
  'pShareName': '', 
  'pPortName': 'USB001', 
  'pDriverName': 'POSSTORE PS-7 Windows Driver', 
  'pComment': '', 
  'pLocation': '', 
  'pDevMode': <PyDEVMODEW object at 0x000001ED754B5450>, 
  'pSepFile': '', 
  'pPrintProcessor': 'winprint', 
  'pDatatype': 'RAW', 
  'pParameters': '', 
  'pSecurityDescriptor': <PySECURITY_DESCRIPTOR object at 0x000001ED754A5DE0>, 
  'Attributes': 576, 
  'Priority': 1, 'DefaultPriority': 0, 
  'StartTime': 0, 
  'UntilTime': 0, 
  'Status': 0, 
  'cJobs': 0, 
  'AveragePPM': 0
  }
